Running dataPrep.py, GenTrain
dataPrep.py's GenTrain took  0.536466121674 seconds to run
 
Running dataPrepdigit.py, GenPatches
dataPrepdigit.py's GenPatches took  17.4359600544 seconds to run
 
You have chosen: Namespace(f1=4900, f2=35, f3=10, lamb=0.0001, m=60000, numfiles=40, pooldim=7)
 
Grabbing the convolved and pooled data...
Grabbing file: 1
Grabbing file: 2
Grabbing file: 3
Grabbing file: 4
Grabbing file: 5
Grabbing file: 6
Grabbing file: 7
Grabbing file: 8
Grabbing file: 9
Grabbing file: 10
Grabbing file: 11
Grabbing file: 12
Grabbing file: 13
Grabbing file: 14
Grabbing file: 15
Grabbing file: 16
Grabbing file: 17
Grabbing file: 18
Grabbing file: 19
Grabbing file: 20
Grabbing file: 21
Grabbing file: 22
Grabbing file: 23
Grabbing file: 24
Grabbing file: 25
Grabbing file: 26
Grabbing file: 27
Grabbing file: 28
Grabbing file: 29
Grabbing file: 30
Grabbing file: 31
Grabbing file: 32
Grabbing file: 33
Grabbing file: 34
Grabbing file: 35
Grabbing file: 36
Grabbing file: 37
Grabbing file: 38
Grabbing file: 39
Grabbing file: 40
cpdat shape (49000000,)
Got the data
 
Running dataPrep.py, GenTest
dataPrep.py's GenTest took  0.35679602623 seconds to run
 
shape of images (10000, 784)
(171895,) (10000, 4900)
Number of data points identified correctly per number:
[ 965.,1124., 999., 984., 958., 868., 930., 993., 942., 968.]
 
Number of total data points identified correctly: 9731.0
 
Percent correct per number:
[0.98469388,0.99030837,0.96802326,0.97425743,0.97556008,0.97309417,
 0.97077244,0.96595331,0.96714579,0.95936571]
 
Total percent correct: 0.9731
Traceback (most recent call last):
  File "cnnVisualdigit.py", line 216, in <module>
    ConfuMat(a3, y)
  File "cnnVisualdigit.py", line 143, in ConfuMat
    fig, ax = plt.subplots(figsize=(10, 10)) # (width, height) in inches
  File "/usr/local/anaconda/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1077, in subplots
    fig = figure(**fig_kw)
  File "/usr/local/anaconda/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 434, in figure
    **kwargs)
  File "/usr/local/anaconda/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 47, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/usr/local/anaconda/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 54, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/usr/local/anaconda/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 72, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/usr/local/anaconda/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/usr/local/anaconda/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 139, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
